# Generated by Django 5.1.2 on 2024-11-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='country',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='state',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
