# Generated by Django 5.1.2 on 2025-01-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usermodel_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='account_type',
            field=models.CharField(choices=[('individual', 'individual'), ('influencer', 'influencer'), ('expert', 'expert'), ('business', 'business')], max_length=255, null=True),
        ),
    ]
