# Generated by Django 5.2 on 2025-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_usermodel_account_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermodel", name="account_type",),
    ]
