# Generated by Django 5.2 on 2025-04-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_usermodel_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="google_id",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
