# Generated by Django 5.2 on 2025-05-02 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_userdevices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevices",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
