# Generated by Django 5.2 on 2025-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_userdevices_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevices",
            name="fcm_token",
            field=models.TextField(null=True),
        ),
    ]
