# Generated by Django 5.2 on 2025-05-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_userdevices_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
