# Generated by Django 5.2 on 2025-05-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_usermodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="currency",
            field=models.CharField(default="USD", max_length=200, null=True),
        ),
    ]
