# Generated by Django 5.2 on 2025-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_usermodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bvn',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_dob',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_first_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_last_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_phone',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='has_bvn',
            field=models.BooleanField(default=True),
        ),
    ]
