# Generated by Django 5.2 on 2025-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usermodel_bvn_usermodel_bvn_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='account_tier',
            field=models.CharField(default='Tier 1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='has_bvn',
            field=models.BooleanField(default=False),
        ),
    ]
