# Generated by Django 5.2 on 2025-09-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_usermodel_account_tier_alter_usermodel_has_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='embedly_customer_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='embedly_wallet_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
