# Generated by Django 5.2 on 2025-09-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_usermodel_dob_usermodel_embedly_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bvn_gender',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
