# Generated by Django 5.2 on 2025-09-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_usermodel_bvn_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bvn_enrollment_bank',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_marital_status',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_nationality',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_residential_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_state_of_residence',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bvn_watch_listed',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
