# Generated by Django 5.2 on 2025-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_usermodel_bvn_enrollment_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='has_virtual_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
