# Generated by Django 5.2 on 2025-09-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_usermodel_has_virtual_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
