# Generated by Django 5.2 on 2025-09-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_usermodel_groups_usermodel_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevices',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Device', 'verbose_name_plural': 'User Devices'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table=None,
        ),
    ]
