# Generated by Django 5.2 on 2025-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_userdevices_options_alter_usermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='has_nin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin',
            field=models.CharField(default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_dob',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_first_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_gender',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_last_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_marital_status',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_nationality',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_phone',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_residential_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nin_state_of_residence',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
