# Generated by Django 5.2 on 2025-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_usermodel_has_nin_usermodel_nin_usermodel_nin_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='transaction_pin',
            field=models.CharField(help_text='Hashed transaction PIN for withdrawals', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='transaction_pin_set',
            field=models.BooleanField(default=False, help_text='Whether user has set a transaction PIN'),
        ),
    ]


