# Generated by Django 4.2.25 on 2025-11-11 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_v2_mobile_schema_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userbankaccount',
            new_name='user_bank_a_user_id_0d58a0_idx',
            old_name='user_bank_a_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userbankaccount',
            new_name='user_bank_a_account_36e1d2_idx',
            old_name='user_bank_a_account_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_user_id_bb1b83_idx',
            old_name='user_sessio_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_refresh_a1321c_idx',
            old_name='user_sessio_refresh__idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_device__4ac8e0_idx',
            old_name='user_sessio_device__idx',
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='apple_id',
            field=models.CharField(default='', help_text='Apple User ID for Apple Sign In', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
