# Generated by Django 4.2.25 on 2025-11-19 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0024_rename_user_bank_a_user_id_idx_user_bank_a_user_id_0d58a0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('account', 'Account Issue'), ('wallet', 'Wallet/Transaction Issue'), ('withdrawal', 'Withdrawal Issue'), ('savings', 'Savings Goal Issue'), ('verification', 'Verification/KYC Issue'), ('security', 'Security Concern'), ('technical', 'Technical Issue'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], db_index=True, default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject/title for this note', max_length=200)),
                ('note', models.TextField(help_text='Detailed note about the interaction or issue')),
                ('resolution', models.TextField(blank=True, help_text='How the issue was resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('internal_only', models.BooleanField(default=False, help_text='If true, this note is for internal use only and should not be shared with customer')),
                ('flagged', models.BooleanField(default=False, help_text='Flag for escalation or special attention')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Support staff member who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Support staff member who resolved this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The customer this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='support_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Note',
                'verbose_name_plural': 'Customer Notes',
                'db_table': 'customer_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='customer_no_user_id_65103f_idx'), models.Index(fields=['status', 'priority'], name='customer_no_status_fa47ed_idx'), models.Index(fields=['category', '-created_at'], name='customer_no_categor_76d5bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('custom', 'Custom Action')], db_index=True, max_length=20)),
                ('action_description', models.CharField(help_text='Human-readable description of the action', max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=255)),
                ('changes', models.JSONField(blank=True, help_text='JSON of fields that were changed (before/after values)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Staff member who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='admin_audit_user_id_3d5dfd_idx'), models.Index(fields=['content_type', 'object_id'], name='admin_audit_content_d76340_idx'), models.Index(fields=['action', '-timestamp'], name='admin_audit_action_a227ce_idx')],
            },
        ),
    ]
