# Generated by Django 5.1.4 on 2026-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_customernote_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='nudge_wallet_setup_sent',
            field=models.BooleanField(default=False, help_text='Whether wallet setup nudge has been sent'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
