[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:web]
command=gunicorn gidinest_backend.wsgi --bind 0.0.0.0:8080 --workers 2 --log-file -
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A gidinest_backend worker -l info --concurrency 2
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
