# Generated by Django 4.2.25 on 2025-11-19 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('logger_name', models.CharField(db_index=True, help_text="Name of the logger (e.g., 'django.request')", max_length=255)),
                ('message', models.TextField(help_text='Log message')),
                ('pathname', models.CharField(blank=True, help_text='File path where log originated', max_length=500, null=True)),
                ('function_name', models.CharField(blank=True, help_text='Function name where log originated', max_length=255, null=True)),
                ('line_number', models.IntegerField(blank=True, help_text='Line number where log originated', null=True)),
                ('exception', models.TextField(blank=True, help_text='Exception traceback if available', null=True)),
                ('request_path', models.CharField(blank=True, db_index=True, help_text='HTTP request path if available', max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP request method (GET, POST, etc.)', max_length=10, null=True)),
                ('user_email', models.EmailField(blank=True, db_index=True, help_text='User email if authenticated', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Server Log',
                'verbose_name_plural': 'Server Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='core_server_timesta_246a4f_idx'), models.Index(fields=['logger_name', '-timestamp'], name='core_server_logger__40579f_idx')],
            },
        ),
    ]
