# Generated by Django 5.2 on 2025-07-19 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal')], help_text='Type of transaction (e.g., contribution to goal, withdrawal from goal).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the transaction for this specific goal.', max_digits=15)),
                ('description', models.CharField(blank=True, help_text='Optional description for the goal transaction.', max_length=255, null=True)),
                ('goal_current_amount', models.DecimalField(decimal_places=2, help_text='Amount saved in the goal after this transaction occurred.', max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(help_text='The savings goal involved in this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsgoalmodel')),
            ],
            options={
                'verbose_name': 'Savings Goal Transaction',
                'verbose_name_plural': 'Savings Goal Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
