# Generated by Django 5.2 on 2025-09-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsgoaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoalmodel',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Interest rate on the goal', max_digits=15),
        ),
    ]
