# Generated by Django 5.2 on 2025-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savingsgoalmodel_accrued_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoalmodel',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest accrued on the goal', max_digits=15),
        ),
    ]
