# Generated by Django 4.2.25 on 2025-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savingsgoalmodel_accrued_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoalmodel',
            name='early_withdrawal_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty percentage for early withdrawal (e.g., 5.00 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='savingsgoalmodel',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether withdrawals are locked until maturity date'),
        ),
        migrations.AddField(
            model_name='savingsgoalmodel',
            name='lock_period_months',
            field=models.IntegerField(blank=True, help_text='Duration of lock period in months (e.g., 3, 6, 12)', null=True),
        ),
        migrations.AddField(
            model_name='savingsgoalmodel',
            name='maturity_date',
            field=models.DateTimeField(blank=True, help_text='Date when the locked goal matures and becomes withdrawable', null=True),
        ),
    ]
