# Generated by Django 4.2.25 on 2025-12-04 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_delete_alertsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('wallet_deposit', 'Wallet Deposit'), ('wallet_withdrawal_requested', 'Withdrawal Requested'), ('wallet_withdrawal_approved', 'Withdrawal Approved'), ('wallet_withdrawal_failed', 'Withdrawal Failed'), ('goal_created', 'Goal Created'), ('goal_funded', 'Goal Funded'), ('goal_withdrawn', 'Goal Withdrawn'), ('goal_milestone', 'Goal Milestone'), ('goal_completed', 'Goal Completed'), ('goal_unlocked', 'Goal Unlocked'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('comment_replied', 'Comment Replied'), ('challenge_joined', 'Challenge Joined'), ('challenge_completed', 'Challenge Completed'), ('group_joined', 'Group Joined'), ('verification_completed', 'Verification Completed'), ('account_upgraded', 'Account Upgraded'), ('security_alert', 'Security Alert'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_c4d245_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx')],
            },
        ),
    ]
