# Generated by Django 5.1.4 on 2026-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('wallet_deposit', 'Wallet Deposit'), ('wallet_withdrawal_requested', 'Withdrawal Requested'), ('wallet_withdrawal_approved', 'Withdrawal Approved'), ('wallet_withdrawal_failed', 'Withdrawal Failed'), ('goal_created', 'Goal Created'), ('goal_funded', 'Goal Funded'), ('goal_withdrawn', 'Goal Withdrawn'), ('goal_milestone', 'Goal Milestone'), ('goal_completed', 'Goal Completed'), ('goal_unlocked', 'Goal Unlocked'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('comment_replied', 'Comment Replied'), ('challenge_joined', 'Challenge Joined'), ('challenge_completed', 'Challenge Completed'), ('group_joined', 'Group Joined'), ('gift_received', 'Gift Received'), ('gift_milestone', 'Gift Milestone'), ('fund_target_reached', 'Fund Target Reached'), ('verification_completed', 'Verification Completed'), ('account_upgraded', 'Account Upgraded'), ('security_alert', 'Security Alert'), ('system_announcement', 'System Announcement'), ('wallet_setup_nudge', 'Wallet Setup Nudge')], max_length=50),
        ),
    ]
