# Generated by Django 5.2 on 2025-07-19 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the community post.', max_length=255)),
                ('content', models.TextField(help_text='Full content of the community post.')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes the post has received.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last updated.')),
                ('author', models.ForeignKey(help_text='The user who created this post.', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Post',
                'verbose_name_plural': 'Community Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the comment was last updated.')),
                ('author', models.ForeignKey(help_text='The user who created this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The post this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
            ],
            options={
                'verbose_name': 'Community Comment',
                'verbose_name_plural': 'Community Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
