# Generated by Django 5.2 on 2025-07-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes the post has received.'),
        ),
    ]
