# Generated by Django 4.2.25 on 2025-12-03 10:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_communitypost_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Current amount saved for this challenge.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Challenge Participation',
                'verbose_name_plural': 'Challenge Participations',
                'ordering': ['-current_amount'],
            },
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the community group.', max_length=255)),
                ('description', models.TextField(help_text='Description of the community group.')),
                ('category', models.CharField(choices=[('pregnancy', 'Pregnancy & Expecting'), ('new_parents', 'New Parents'), ('general_savings', 'General Savings'), ('childbirth', 'Childbirth'), ('parenting', 'Parenting'), ('other', 'Other')], default='other', max_length=50)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('badge', models.CharField(choices=[('active', 'Active'), ('popular', 'Popular'), ('featured', 'Featured'), ('new', 'New'), ('none', 'None')], default='none', max_length=20)),
                ('icon', models.URLField(blank=True, help_text='URL to group icon/image.', null=True)),
                ('cover_image', models.URLField(blank=True, help_text='URL to group cover image.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the group is active.')),
            ],
            options={
                'verbose_name': 'Community Group',
                'verbose_name_plural': 'Community Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Current rank in the group.')),
                ('previous_rank', models.PositiveIntegerField(blank=True, help_text='Previous rank for trending.', null=True)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, help_text='Total savings amount.', max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Leaderboard',
                'verbose_name_plural': 'Group Leaderboards',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is active.')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the challenge.', max_length=255)),
                ('description', models.TextField(help_text='Description of the challenge.')),
                ('icon', models.URLField(blank=True, help_text='URL to challenge icon.', null=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='Target savings amount for the challenge.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('reward', models.CharField(blank=True, help_text='Reward for completing the challenge.', max_length=255)),
                ('reward_description', models.TextField(blank=True, help_text='Detailed description of the reward.')),
                ('start_date', models.DateTimeField(help_text='When the challenge starts.')),
                ('end_date', models.DateTimeField(help_text='When the challenge ends.')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Savings Challenge',
                'verbose_name_plural': 'Savings Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection.', null=True),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/moderator who reviewed this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of comments on the post.'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to attached image.', null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection.', null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/moderator who reviewed this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views the post has received.'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'status', 'created_at'], name='community_c_post_id_62e2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status', '-created_at'], name='community_c_status_012a6e_idx'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this challenge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='group',
            field=models.ForeignKey(help_text='The group this challenge belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(help_text='The post that was liked.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(help_text='The user who liked the post.', on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(help_text='The group this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member.', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupleaderboard',
            name='group',
            field=models.ForeignKey(help_text='The group this leaderboard entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='groupleaderboard',
            name='user',
            field=models.ForeignKey(help_text='The user on the leaderboard.', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='challenge',
            field=models.ForeignKey(help_text='The challenge being participated in.', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='community.savingschallenge'),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='user',
            field=models.ForeignKey(help_text='The user participating in the challenge.', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group this post belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.communitygroup'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['group', 'status', '-created_at'], name='community_c_group_i_3acb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='savingschallenge',
            index=models.Index(fields=['group', 'status', '-created_at'], name='community_s_group_i_57fcba_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='community_p_post_id_69bd9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupleaderboard',
            index=models.Index(fields=['group', 'rank'], name='community_g_group_i_b48237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupleaderboard',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['challenge', '-current_amount'], name='community_c_challen_e83d90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('challenge', 'user')},
        ),
    ]
