# Generated by Django 5.1.4 on 2026-04-03 08:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Baby Ade's Arrival Fund'", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fundraising target', max_digits=15, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Expected due date / event date', null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('thank_you_message', models.TextField(default='Thank you for your generous gift!', help_text='Shown to contributor after successful payment')),
                ('show_contributors', models.CharField(choices=[('public', 'Public - Show name and amount'), ('private', 'Private - Show only name'), ('anonymous', 'Anonymous - Hide all contributor details')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross gift amount', max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount credited to mother after 1.5% fee', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, default='', max_length=255)),
                ('contributor_name', models.CharField(max_length=255)),
                ('contributor_email', models.EmailField(blank=True, default='', help_text='Optional — used for Paystack + receipt email', max_length=254)),
                ('contributor_phone', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.TextField(blank=True, default='', help_text='Personal message to the mother')),
                ('baby_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gifting.babyfund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='babyfund',
            index=models.Index(fields=['user', 'is_active'], name='gifting_bab_user_id_992cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['baby_fund', 'status'], name='gifting_gif_baby_fu_c9229b_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['paystack_reference'], name='gifting_gif_paystac_9124d1_idx'),
        ),
    ]
