"""
Django settings for gidinest_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from decouple import Config, RepositoryEnv
import pymysql
pymysql.install_as_MySQLdb()


config = Config(RepositoryEnv('.env'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', config('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', config('DEBUG', default=False, cast=bool))

ALLOWED_HOSTS = [
    "api.gidinest.com",
    "app.gidinest.com",
    "gidinest.com",
    "www.gidinest.com",
    "localhost",
    "127.0.0.1",
    "192.168.8.2",
    "192.168.100.2",
    "192.168.1.63",
    "167.99.120.170",  # Your DigitalOcean server IP
    "172.20.10.7",   # Current local network IP for mobile testing
    "172.20.10.11",  # Previous local network IP for mobile testing
    "0.0.0.0",  # Development server
]


# Application definition
INSTALLED_APPS = [
    'jazzmin',  # Modern admin theme - must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS headers support
    'rest_framework',  # Django REST framework
    'drf_spectacular',  # OpenAPI 3.0 schema generation for Swagger
    'django_celery_beat',  # Celery periodic tasks
    'django_celery_results',  # Celery task results
    'core',
    'account',
    'onboarding',
    'notification',
    'savings',
    'wallet',
    'community',
    'providers',
    'dashboard',  # V2 Mobile - Unified dashboard
    'transactions',  # V2 Mobile - Comprehensive transactions
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gidinest_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gidinest_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', config('DB_NAME')),  
        'USER': os.getenv('DB_USER', config('DB_USER')),   
        'PASSWORD': os.getenv('DB_PASSWORD', config('DB_PASSWORD')),
        'HOST': os.getenv('DB_HOST', config('DB_HOST')), 
        'PORT': '3306',          
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic puts files

# Optional: better compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




AUTH_USER_MODEL = "account.UserModel"





ZEPTOMAIL_API_KEY = os.getenv('ZEPTOMAIL_API_KEY', config('ZEPTOMAIL_API_KEY'))

ZEPTOMAIL_FROM_EMAIL = "noreply@gidinest.com"


PREMBLY_API_KEY=os.getenv('PREMBLY_API_KEY', config('PREMBLY_API_KEY'))


# 9PSB (9 Payment Service Bank) Configuration - V2 Wallet Provider
PSB9_USERNAME = os.getenv('PSB9_USERNAME', config('PSB9_USERNAME', default=''))
PSB9_PASSWORD = os.getenv('PSB9_PASSWORD', config('PSB9_PASSWORD', default=''))
PSB9_CLIENT_ID = os.getenv('PSB9_CLIENT_ID', config('PSB9_CLIENT_ID', default=''))
PSB9_CLIENT_SECRET = os.getenv('PSB9_CLIENT_SECRET', config('PSB9_CLIENT_SECRET', default=''))
PSB9_BASE_URL = os.getenv('PSB9_BASE_URL', config('PSB9_BASE_URL', default='http://102.216.128.75:9090'))
PSB9_MERCHANT_ID = os.getenv('PSB9_MERCHANT_ID', config('PSB9_MERCHANT_ID', default=''))


CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://gidinest.com",
    "https://www.gidinest.com",
    "https://app.gidinest.com",
    "https://api.gidinest.com",
    # Local development URLs
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3039",  # Your current frontend port
    "http://localhost:5173",  # Vite default port
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3039",  # Your current frontend port
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'api-key',
    'Access-Control-Allow-Origin',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight requests for 24 hours


REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
         'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 30,

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend', # Enable django-filter globally
        'rest_framework.filters.SearchFilter', # Enable search globally
        'rest_framework.filters.OrderingFilter', # Enable ordering globally
    ],

    # Custom exception handler for consistent error format
    'EXCEPTION_HANDLER': 'core.helpers.exceptions.custom_exception_handler',

    # drf-spectacular settings for OpenAPI schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


SIMPLE_JWT = {
    # V2 Mobile: Short-lived access tokens (1 hour) for better security
    # V1 Web: Can use refresh token to get new access tokens
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Changed from 14 days to 1 hour for V2
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Refresh tokens remain valid for 30 days
    'ROTATE_REFRESH_TOKENS': True,  # Enable token rotation for better security
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens after rotation
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}


# drf-spectacular OpenAPI settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'GidiNest API',
    'DESCRIPTION': '''
    # GidiNest API Documentation

    ## 🎯 Choose Your API Version

    ### **Building a Web Application?**
    👉 Use **V1 API** - Filter by tags starting with "V1"
    - Base URL: `/api/v1/`
    - Status: **Production - FROZEN** (stable, no breaking changes)
    - Purpose: Web dashboard and admin portal
    - Quick Start: See `/docs/frontend/QUICK_START.md`

    ### **Building a Mobile Application (iOS/Android)?**
    👉 Use **V2 API** - Filter by tags starting with "V2"
    - Base URL: `/api/v2/`
    - Status: **Active Development** (new features added regularly)
    - Purpose: Native mobile apps
    - Quick Start: See `/docs/mobile/QUICK_START.md`

    ---

    ## 🔐 Authentication

    All endpoints (except registration and login) require JWT authentication.
    
    **Header Format:**
    ```
    Authorization: Bearer <access_token>
    ```

    **Token Differences:**
    - **V1 (Web):** Longer-lived tokens suitable for web sessions
    - **V2 (Mobile):** Short-lived tokens (1 hour) with refresh mechanism

    ---

    ## 📊 Response Format

    All responses follow a standard structure:
    ```json
    {
      "success": true|false,
      "message": "Human-readable message",
      "data": { /* Response data */ }
    }
    ```

    ---

    ## 🔍 Using This Documentation

    1. **Filter by Platform:** Use the tag filter to show only V1 (Web) or V2 (Mobile) endpoints
    2. **Test Endpoints:** Click "Try it out" to test endpoints directly
    3. **Authorize:** Click the "Authorize" button to add your JWT token
    4. **View Examples:** See request/response examples for each endpoint

    ---

    ## 📚 Additional Resources

    - **API Guide:** `/docs/API_GUIDE.md`
    - **Frontend Guide:** `/docs/frontend/QUICK_START.md`
    - **Mobile Guide:** `/docs/mobile/QUICK_START.md`
    - **Legacy Docs:** `/docs/api/` (markdown files)

    ---

    **Note:** This documentation is auto-generated from code and always up-to-date.
    ''',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'docExpansion': 'none',
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVERS': [
        {'url': 'https://api.gidinest.com', 'description': 'Production Server'},
        {'url': 'http://localhost:8000', 'description': 'Local Development Server'},
    ],
    'EXTERNAL_DOCS': {
        'description': 'Full API Documentation',
        'url': 'https://docs.gidinest.com',
    },
    'TAGS': [
        {'name': 'V1 - Authentication', 'description': 'Web app authentication endpoints'},
        {'name': 'V1 - Account', 'description': 'Web app account management'},
        {'name': 'V1 - Wallet', 'description': 'Web app wallet operations'},
        {'name': 'V1 - Savings', 'description': 'Web app savings goals'},
        {'name': 'V1 - Community', 'description': 'Web app community posts'},
        {'name': 'V2 - Auth', 'description': 'Mobile app authentication'},
        {'name': 'V2 - Dashboard', 'description': 'Mobile app dashboard'},
        {'name': 'V2 - Profile', 'description': 'Mobile app profile management'},
        {'name': 'V2 - Wallet', 'description': 'Mobile app wallet operations'},
        {'name': 'V2 - Transactions', 'description': 'Mobile app transactions'},
        {'name': 'V2 - Savings', 'description': 'Mobile app savings goals'},
        {'name': 'V2 - Community', 'description': 'Mobile app community'},
        {'name': 'V2 - Notifications', 'description': 'Mobile app notifications'},
        {'name': 'V2 - KYC', 'description': 'Mobile app KYC verification'},
    ],
    'SECURITY': [{'bearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}



SAVINGS_TEMPLATES=["Delivery Day Fund","Baby Essentials","Immunization Trip"]




EMBEDLY_API_KEY_DEV=os.getenv('EMBEDLY_API_KEY_DEV', config('EMBEDLY_API_KEY_DEV')) 
EMBEDLY_ORGANIZATION_ID_DEV=os.getenv('EMBEDLY_ORGANIZATION_ID_DEV', config('EMBEDLY_ORGANIZATION_ID_DEV')) 


EMBEDLY_ORGANIZATION_ID_PRODUCTION=os.getenv('EMBEDLY_ORGANIZATION_ID_PRODUCTION', config('EMBEDLY_ORGANIZATION_ID_PRODUCTION'))
EMBEDLY_API_KEY_PRODUCTION=os.getenv('EMBEDLY_API_KEY_PRODUCTION', config('EMBEDLY_API_KEY_PRODUCTION'))
EMBEDLY_WEBHOOK_SECRET=os.getenv('EMBEDLY_WEBHOOK_SECRET', config('EMBEDLY_WEBHOOK_SECRET', default=''))
EMBEDLY_CUSTOMER_TYPE_ID_INDIVIDUAL=os.getenv('EMBEDLY_CUSTOMER_TYPE_ID_INDIVIDUAL', config('EMBEDLY_CUSTOMER_TYPE_ID_INDIVIDUAL'))
EMBEDLY_COUNTRY_ID_NIGERIA=os.getenv('EMBEDLY_COUNTRY_ID_NIGERIA', config('EMBEDLY_COUNTRY_ID_NIGERIA'))
EMBEDLY_CURRENCY_ID_NGN = config('EMBEDLY_CURRENCY_ID_NGN', default='')
BASE_URL = os.getenv('BASE_URL', 'https://app.gidinest.com')
CUORAL_API_KEY=os.getenv('CUORAL_API_KEY', config('CUORAL_API_KEY'))   

ACTIVATION_URL="https://app.gidinest.com/email/activation/"


CSRF_TRUSTED_ORIGINS = [
    "https://gidinest.com",
    "https://www.gidinest.com",
    "https://app.gidinest.com",
    "https://api.gidinest.com",
    # Local development
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3039",  # Your current frontend port
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3039",  # Your current frontend port
    "http://127.0.0.1:5173",
    # Mobile app local network testing
    "http://172.20.10.7:8000",
    "http://172.20.10.11:8000",
]


PAYSTACK_SECRET_KEY=os.getenv('PAYSTACK_SECRET_KEY', config('PAYSTACK_SECRET_KEY'))


# Celery Configuration
# =====================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', config('CELERY_BROKER_URL', default='redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0'))

# Optional: Use django-celery-results for storing task results in database
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_CACHE_BACKEND = 'django-cache'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit at 25 minutes

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Beat scheduler settings (for periodic tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Django Ratelimit Configuration
# Fix for reverse proxy (Nginx) with Unix sockets
RATELIMIT_USE_CACHE = 'default'


# =====================
# LOGGING CONFIGURATION
# =====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'database': {
            'class': 'core.logging_handler.DatabaseLogHandler',
            'level': 'INFO',  # Only log INFO and above to database
        },
        'database_errors': {
            'class': 'core.logging_handler.DatabaseLogHandler',
            'level': 'ERROR',  # Separate handler for errors only
        },
    },
    'loggers': {
        # Django framework loggers
        'django': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'database_errors'],
            'level': 'ERROR',  # Captures all 4xx and 5xx errors
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],  # Only console for DB queries (too verbose for database)
            'level': 'WARNING',  # Only log slow queries and errors
            'propagate': False,
        },

        # Application loggers - all GidiNest apps
        'account': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'wallet': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'savings': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'onboarding': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'community': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'providers': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'dashboard': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'transactions': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'notification': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },

        # Celery tasks (if you want to log background tasks)
        'celery': {
            'handlers': ['console', 'database'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# ==============================================
# JAZZMIN ADMIN UI CONFIGURATION
# ==============================================

JAZZMIN_SETTINGS = {
    # Title on the login screen and browser tab
    "site_title": "GidiNest Admin",
    "site_header": "GidiNest Internal Admin",
    "site_brand": "GidiNest",
    "site_logo": None,  # Path to logo (optional)
    "login_logo": None,  # Path to login logo (optional)
    "site_logo_classes": "img-circle",
    "site_icon": None,  # Favicon path (optional)

    # Welcome text on the login screen
    "welcome_sign": "Welcome to GidiNest Admin Portal",

    # Copyright on the footer
    "copyright": "GidiNest Ltd",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": ["account.UserModel", "account.CustomerNote"],

    # Field name on user model that contains avatar
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support Dashboard", "url": "support_dashboard", "permissions": ["auth.view_user"]},
        {"model": "account.CustomerNote"},
        {"app": "wallet"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right
    "usermenu_links": [
        {"name": "Support Dashboard", "url": "support_dashboard", "icon": "fas fa-headset"},
        {"model": "account.UserModel"},
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu
    "hide_apps": [],

    # Hide these models when generating side menu
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of
    "order_with_respect_to": [
        "account",
        "wallet",
        "savings",
        "transactions",
        "dashboard",
        "community",
        "notification",
        "onboarding",
        "providers",
        "core",
    ],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "account": [{
            "name": "Support Dashboard",
            "url": "support_dashboard",
            "icon": "fas fa-chart-line",
            "permissions": ["account.view_usermodel"]
        }]
    },

    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "account": "fas fa-user-circle",
        "account.UserModel": "fas fa-users",
        "account.UserSession": "fas fa-laptop",
        "account.UserDevices": "fas fa-mobile-alt",
        "account.UserBankAccount": "fas fa-university",
        "account.CustomerNote": "fas fa-sticky-note",
        "account.AdminAuditLog": "fas fa-history",

        "wallet": "fas fa-wallet",
        "wallet.Wallet": "fas fa-wallet",
        "wallet.WalletTransaction": "fas fa-exchange-alt",
        "wallet.WithdrawalRequest": "fas fa-money-bill-wave",

        "savings": "fas fa-piggy-bank",
        "savings.SavingsGoal": "fas fa-bullseye",
        "savings.SavingsContribution": "fas fa-plus-circle",

        "transactions": "fas fa-receipt",
        "transactions.Transaction": "fas fa-file-invoice-dollar",

        "dashboard": "fas fa-tachometer-alt",

        "community": "fas fa-users",
        "community.CommunityGroup": "fas fa-users",
        "community.CommunityPost": "fas fa-comment",

        "notification": "fas fa-bell",
        "notification.Notification": "fas fa-envelope",

        "onboarding": "fas fa-user-plus",

        "providers": "fas fa-plug",

        "core": "fas fa-cog",
        "core.ServerLog": "fas fa-server",

        "django_celery_beat": "fas fa-clock",
        "django_celery_results": "fas fa-tasks",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################

    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############

    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,

    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,

    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############

    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",

    # Override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "account.UserModel": "horizontal_tabs",
    },

    # Add a language dropdown into the admin
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",  # Options: default, cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, yeti
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
