# Generated by Django 5.2 on 2025-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(help_text='The name on the bank account.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(help_text='Unique virtual account number for the wallet.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank',
            field=models.CharField(default='Providus Bank', help_text='The bank where the virtual account is held.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(default='001', help_text='The bank code where the virtual account is held.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='embedly_wallet_id',
            field=models.CharField(blank=True, help_text='The Embedly wallet ID associated with this wallet.', max_length=200, null=True),
        ),
    ]
