# Generated by Django 5.2 on 2025-09-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank',
            field=models.CharField(default='', help_text='The bank where the virtual account is held.', max_length=100, null=True),
        ),
    ]
