# Generated by Django 5.2 on 2025-10-05 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the transaction for this specific goal.', max_digits=15)),
                ('description', models.CharField(blank=True, help_text='Optional description for the goal transaction.', max_length=255, null=True)),
                ('sender_name', models.CharField(help_text='Name of sender', max_length=255, null=True)),
                ('sender_account', models.CharField(help_text='Account of sender', max_length=255, null=True)),
                ('wallet', models.ForeignKey(help_text='The wallet associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
