# Generated by Django 5.2 on 2025-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='external_reference',
            field=models.CharField(help_text='Reference from external system', max_length=255, null=True, unique=True),
        ),
    ]
