# Generated by Django 5.2 on 2025-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_wallettransaction_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_account_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
