# Generated by Django 4.2.25 on 2025-11-12 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savingsgoalmodel_accrued_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0007_withdrawalrequest_bank_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, help_text='Unique token for accessing the payment link', max_length=64, unique=True)),
                ('link_type', models.CharField(choices=[('wallet', 'Wallet Funding'), ('savings_goal', 'Savings Goal Contribution'), ('event', 'Event Funding')], default='wallet', help_text='Type of payment link', max_length=20)),
                ('event_name', models.CharField(blank=True, help_text="Name of the event (e.g., 'Baby Shower - March 2025')", max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, help_text='Date of the event', null=True)),
                ('event_description', models.TextField(blank=True, help_text='Description of the event or purpose', null=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional target amount for progress tracking', max_digits=15, null=True)),
                ('allow_custom_amount', models.BooleanField(default=True, help_text='Allow contributors to pay any amount')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount if allow_custom_amount is False', max_digits=15, null=True)),
                ('show_contributors', models.CharField(choices=[('public', 'Public - Show name and amount'), ('private', 'Private - Show only name'), ('anonymous', 'Anonymous - Hide all contributor details')], default='public', help_text='Privacy setting for contributor list', max_length=20)),
                ('custom_message', models.TextField(blank=True, help_text='Thank you message shown after successful payment', null=True)),
                ('description', models.TextField(blank=True, help_text='Description shown on the payment link page', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the link is active and accepting payments')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date for the link', null=True)),
                ('one_time_use', models.BooleanField(default=False, help_text='Deactivate link after first successful payment')),
                ('used', models.BooleanField(default=False, help_text='Track if one-time link has been used')),
                ('savings_goal', models.ForeignKey(blank=True, help_text='Linked savings goal (if link_type is savings_goal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='savings.savingsgoalmodel')),
                ('user', models.ForeignKey(help_text='The user who owns this payment link', on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkContribution',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount contributed', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the contribution', max_length=20)),
                ('contributor_name', models.CharField(blank=True, help_text='Name of the contributor (if provided)', max_length=255, null=True)),
                ('contributor_email', models.EmailField(blank=True, help_text='Email of the contributor (if provided)', max_length=254, null=True)),
                ('contributor_phone', models.CharField(blank=True, help_text='Phone of the contributor (if provided)', max_length=20, null=True)),
                ('external_reference', models.CharField(help_text='External payment reference from payment provider', max_length=255, unique=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from contributor', null=True)),
                ('payment_link', models.ForeignKey(help_text='The payment link this contribution is for', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='wallet.paymentlink')),
                ('wallet_transaction', models.ForeignKey(blank=True, help_text='Associated wallet transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_link_contributions', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Payment Link Contribution',
                'verbose_name_plural': 'Payment Link Contributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_link', 'status'], name='wallet_paym_payment_e50094_idx'), models.Index(fields=['external_reference'], name='wallet_paym_externa_4731f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['token'], name='wallet_paym_token_ec2d32_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['user', 'is_active'], name='wallet_paym_user_id_d86710_idx'),
        ),
    ]
