# Generated by Django 5.1.4 on 2026-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_paymentlink_paymentlinkcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='provider_version',
            field=models.CharField(choices=[('v1', 'V1 - Embedly'), ('v2', 'V2 - 9PSB')], default='v1', help_text='Which wallet provider is being used for this wallet.', max_length=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='psb9_account_number',
            field=models.CharField(blank=True, help_text='9PSB account number (for V2 wallets)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='psb9_customer_id',
            field=models.CharField(blank=True, help_text='9PSB customer ID (for V2 wallets)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='psb9_wallet_id',
            field=models.CharField(blank=True, help_text='9PSB wallet ID (for V2 wallets)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Internal transaction reference (e.g., DEB_, CRD_, TRF_ prefixed IDs)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', help_text='Transaction status', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if transfer failed', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='Embedly transaction reference', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
