# Generated by Django 5.1.4 on 2026-02-07 21:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallet_provider_version_wallet_psb9_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_fee_tier1_max', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Upper bound for Tier 1. Amounts <= this get tier1 fee.', max_digits=15)),
                ('transfer_fee_tier1_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Fee for amounts <= tier1_max (e.g., ₦10)', max_digits=10)),
                ('transfer_fee_tier2_max', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Upper bound for Tier 2. Amounts <= this get tier2 fee.', max_digits=15)),
                ('transfer_fee_tier2_amount', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Fee for tier1_max < amount <= tier2_max (e.g., ₦25)', max_digits=10)),
                ('transfer_fee_tier3_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Fee for amounts > tier2_max (e.g., ₦50)', max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0750'), help_text='VAT rate as decimal (0.075 = 7.5%). Applied to fee/commission, NOT principal.', max_digits=5)),
                ('emtl_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Minimum transaction amount to trigger EMTL/Stamp Duty', max_digits=15)),
                ('emtl_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Fixed EMTL/Stamp Duty charge (e.g., ₦50)', max_digits=10)),
                ('payment_link_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Payment link commission rate as decimal (0.05 = 5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration should be active at a time.')),
                ('name', models.CharField(default='Default', help_text='Human-readable name for this config', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about why this config was created/changed', null=True)),
            ],
            options={
                'verbose_name': 'Fee Configuration',
                'verbose_name_plural': 'Fee Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentlinkcontribution',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission deducted from this contribution', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentlinkcontribution',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net amount credited to link owner after fees', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='paymentlinkcontribution',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total fees deducted (commission + VAT)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentlinkcontribution',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT on commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission charged (for payment link transactions)', max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='emtl_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='EMTL/Stamp Duty charged', max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transfer/processing fee charged', max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount after fee deductions (what recipient actually receives)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total fees deducted (fee + vat + emtl + commission)', max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT charged (on fee/commission, not on principal)', max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='fee_config',
            field=models.ForeignKey(blank=True, help_text='Fee configuration active when this transaction was processed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.feeconfiguration'),
        ),
    ]
