# Generated by Django 5.1.4 on 2026-02-07 23:12

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_feeconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_type', models.CharField(choices=[('fee_revenue', 'Fee Revenue')], default='fee_revenue', help_text='Type of platform wallet', max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current accumulated fee revenue', max_digits=15)),
                ('total_transfer_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total of transfer fees collected', max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total of VAT collected', max_digits=15)),
                ('total_emtl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total of EMTL/Stamp Duty collected', max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total of payment link commissions collected', max_digits=15)),
            ],
            options={
                'verbose_name': 'Platform Wallet',
                'verbose_name_plural': 'Platform Wallets',
            },
        ),
    ]
