# Generated by Django 5.1.4 on 2026-04-03 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_platformwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='disbursement_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Withdrawal/disbursement fee rate as decimal (0.01 = 1%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='feeconfiguration',
            name='gift_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0150'), help_text='Gift fee rate as decimal (0.015 = 1.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='total_disbursement_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total of disbursement fees collected (1%)', max_digits=15),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='total_gift_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total of gifting fees collected (1.5%)', max_digits=15),
        ),
    ]
