# Generated by Django 5.2 on 2025-08-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertempdata',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
