# Generated by Django 5.2 on 2025-09-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_registertempdata_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registertempdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registration Session', 'verbose_name_plural': 'Registration Sessions'},
        ),
    ]
