# Generated by Django 4.2.25 on 2025-11-23 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0003_alter_registertempdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey_type', models.CharField(blank=True, choices=[('pregnant', 'Pregnant'), ('trying', 'Trying to Conceive'), ('new_mom', 'New Mom')], help_text="User's pregnancy/motherhood journey stage", max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Expected due date (for pregnant users)', null=True)),
                ('birth_date', models.DateField(blank=True, help_text="Baby's birth date (for new moms)", null=True)),
                ('conception_date', models.DateField(blank=True, help_text='Target conception date (for trying to conceive)', null=True)),
                ('pregnancy_weeks', models.IntegerField(blank=True, help_text='Current pregnancy week (calculated from due date)', null=True)),
                ('hospital_plan', models.CharField(blank=True, choices=[('basic', 'Basic/Public Hospital'), ('private', 'Private Hospital'), ('premium', 'Premium/International Hospital')], help_text='Preferred hospital delivery plan', max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text="User's location (city/state) for cost calculations", max_length=100, null=True)),
                ('baby_essentials_preference', models.CharField(blank=True, choices=[('minimalist', 'Minimalist - Just the Basics'), ('comfort', 'Comfort - Quality Essentials'), ('deluxe', 'Deluxe - Premium Everything')], help_text='Preference level for baby essentials', max_length=20, null=True)),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether user completed the full onboarding flow')),
                ('onboarding_source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='mobile', help_text='Platform where onboarding was completed', max_length=20)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when onboarding was completed', null=True)),
                ('partner_invited', models.BooleanField(default=False, help_text='Whether user invited a partner during onboarding')),
                ('partner_email', models.EmailField(blank=True, help_text="Partner's email if invited", max_length=254, null=True)),
                ('partner_phone', models.CharField(blank=True, help_text="Partner's phone if invited", max_length=20, null=True)),
                ('user', models.OneToOneField(help_text='User who completed this onboarding', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Profile',
                'verbose_name_plural': 'Onboarding Profiles',
                'db_table': 'onboarding_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('mobile_ios', 'Mobile - iOS'), ('mobile_android', 'Mobile - Android')], help_text='Platform/device type', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier (for push notifications)', max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, help_text="Device name/model (e.g., 'iPhone 14 Pro')", max_length=255, null=True)),
                ('app_version', models.CharField(blank=True, help_text='App version running on this device', max_length=50, null=True)),
                ('last_login_at', models.DateTimeField(auto_now=True, help_text='Last time user logged in from this device')),
                ('created_via', models.CharField(choices=[('web', 'Web'), ('mobile_ios', 'Mobile - iOS'), ('mobile_android', 'Mobile - Android')], help_text='Platform where user first registered', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is currently active')),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'db_table': 'user_devices',
                'ordering': ['-last_login_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
